version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: secu4a
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev
    depends_on:
      - postgres
    networks:
      - keycloak-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:azerty@postgres:5432/secu4a
      - KEYCLOAK_JSON_PATH=backend/keycloak.json
    depends_on:
      - postgres
      - keycloak
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    restart: unless-stopped

volumes:
  postgres-data:
  keycloak_data:

networks:
  keycloak-network:
    driver: bridge
