version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: secu4a
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:azerty@postgres:5432/secu4a
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  postgres-data:
