version: '3.8'

services:
  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: projetsecu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev
    depends_on:
      - postgres
    networks:
      - keycloak-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - ./backend/uploads/:/usr/src/app/uploads
      - ./backend/uploads/Public:/usr/src/app/uploads/Public
      - ./backend/uploads/Interne:/usr/src/app/uploads/Interne
      - ./backend/uploads/Confidentiel:/usr/src/app/uploads/Confidentiel
      - ./backend/uploads/Restreint:/usr/src/app/uploads/Restreint
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:azerty@postgres:5432/secu4a
      - KEYCLOAK_JSON_PATH=backend/keycloak.json
    depends_on:
      - postgres
      - keycloak
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth   # Remplacez par votre propre URL
    ports:
      - "8080:8080"
    # volumes:
    #   - ./backend/keycloak:/opt/keycloak/data
    depends_on:
      - postgres
    command:
      - start-dev

volumes:
  postgres-data:
  keycloak_data:

networks:
  keycloak-network:
    driver: bridge
